services:
  - type: web
    name: dataklinik-bot
    env: python
    plan: free        # или ваш платный план
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    region: oregon

    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false

    ports:
      - port: 10000
